services:
  postgres:
    build:
      context: .
      dockerfile: dockerfile
    image: ${IMAGE_NAME}
    container_name: ${PG_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgres/data/${PG_CONTAINER_NAME}
    volumes:
      - db_pam_militares:/var/lib/postgres/data/${PG_CONTAINER_NAME}
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: unless-stopped
volumes:
  db_pam_militares:
    external: true
