CREATE TABLE IF NOT EXISTS militares (
  Id_SERVIDOR_PORTAL VARCHAR(32) NOT NULL,
  NOME VARCHAR(128) NOT NULL,
  CPF VARCHAR(14) NOT NULL,
  MATRICULA VARCHAR(12) NOT NULL,
  DESCRICAO_CARGO VARCHAR(64) NOT NULL,
  CLASSE_CARGO INTEGER,
  REFERENCIA_CARGO INTEGER,
  PADRAO_CARGO INTEGER,
  NIVEL_CARGO INTEGER,
  SIGLA_FUNCAO INTEGER,
  NIVEL_FUNCAO INTEGER,
  FUNCAO VARCHAR(128),
  CODIGO_ATIVIDADE INTEGER,
  ATIVIDADE varchar(128),
  OPCAO_PARCIAL VARCHAR(128),
  COD_UORG_LOTACAO INTEGER,
  UORG_LOTACAO VARCHAR(128),
  COD_ORG_LOTACAO INTEGER,
  ORG_LOTACAO VARCHAR(64),
  COD_ORGSUP_LOTACAO INTEGER,
  ORGSUP_LOTACAO VARCHAR(128),
  COD_UORG_EXERCICIO INTEGER,
  UORG_EXERCICIO VARCHAR(128),
  COD_ORG_EXERCICIO INTEGER,
  ORG_EXERCICIO VARCHAR(128),
  COD_ORGSUP_EXERCICIO INTEGER,
  ORGSUP_EXERCICIO VARCHAR(128),
  COD_TIPO_VINCULO INTEGER,
  TIPO_VINCULO VARCHAR(64),
  SITUACAO_VINCULO VARCHAR(64),
  DATA_INICIO_AFASTAMENTO VARCHAR(16),
  DATA_TERMINO_AFASTAMENTO VARCHAR(16),
  REGIME_JURIDICO VARCHAR(64),
  JORNADA_DE_TRABALHO VARCHAR(128),
  DATA_INGRESSO_CARGOFUNCAO VARCHAR(16),
  DATA_NOMEACAO_CARGOFUNCAO VARCHAR(16),
  DATA_INGRESSO_ORGAO VARCHAR(16),
  DOCUMENTO_INGRESSO_SERVICOPUBLICO VARCHAR(32),
  DATA_DIPLOMA_INGRESSO_SERVICOPUBLICO VARCHAR(32),
  DIPLOMA_INGRESSO_CARGOFUNCAO VARCHAR(128),
  DIPLOMA_INGRESSO_ORGAO VARCHAR(128),
  DIPLOMA_INGRESSO_SERVICOPUBLICO VARCHAR(128),
  UF_EXERCICIO VARCHAR(16)
);


-- COMANDOS SQL


-- SELECIONA TODOS OS MILITARES QUE TIVERAM ALGUMA DATA DE AFASTAMENTO
SELECT * FROM militares WHERE data_inicio_afastamento != '';

-- CONTA TODOS OS MILITARES QUE TIVERAM ALGUMA DATA DE AFASTAMENTO REGISTRADA
SELECT data_inicio_afastamento, count(nome) FROM militares WHERE data_inicio_afastamento != '' GROUP BY data_inicio_afastamento ORDER BY data_inicio_afastamento;


-- CLASSIFICA OS MILITARES POR TIPO DE VÍNCULO
SELECT tipo_vinculo, count(tipo_vinculo) FROM militares GROUP BY tipo_vinculo;

-- CLASSIFICA POR ÓRGÃO DE LOTAÇÃO
SELECT org_lotacao, count(nome) FROM militares GROUP BY org_lotacao;

-- CLASSIFICA POR PATENTE E ÓRGÃO DE LOTAÇÃO
SELECT org_lotacao, descricao_cargo,  count(nome) FROM militares GROUP BY descricao_cargo, org_lotacao ORDER BY org_lotacao;